name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - run: git config --global user.name "${{secrets.GIT_USER}}"
      - run: git config --global user.email "${{secrets.GIT_EMAIL}}"
      - name: Variables
        id: variables
        uses: actions/github-script@v5
        with:
          script: |
            const branch = context.ref.split('/').pop()
            const version = branch.substr(1)
            core.exportVariable('NPM_VERSION_TO_PUBLISH', version)
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: https://registry.npmjs.org
          scope: '@andreashauschild'
      - name: Install dependencies
        run: npm ci
      - run: npm version ${{ env.NPM_VERSION_TO_PUBLISH }}
        working-directory: .
      - run: npm run lib:build --if-present
      - run: npm publish --access public
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
